name: Self-Test

on:
  pull_request:

jobs:
  pull-request-labeler:
    name: Run pull request labeler
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Use Node.js 25
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install package manager handler
        run: npm i -g @antfu/ni --force
        shell: bash

      - name: Install dependencies
        run: ni
        shell: bash

      - name: Build
        run: nr build
        shell: bash

      - name: Check if any code change occured
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Get GitHub App bot user
        if: steps.check-changes.outputs.changes == 'true'
        id: app-user
        run: |
          resp=$(curl -s "https://api.github.com/users/mystique-as-code%5Bbot%5D")
          echo "$resp" | jq
          echo "login<<EOF" >> $GITHUB_OUTPUT
          echo "$(echo "$resp" | jq -r .login)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "id<<EOF" >> $GITHUB_OUTPUT
          echo "$(echo "$resp" | jq -r .id)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git add .
          git config --global user.name "${{ steps.app-user.outputs.login }}"
          git config --global user.email "${{ steps.app-user.outputs.id }}+${{ steps.app-user.outputs.login }}@users.noreply.github.com"
          git commit -m "chore: automatically apply format changes"
          git push origin HEAD:${{ github.head_ref }}

      - name: Run pull request labeler
        uses: "./"
        with:
          github-token: ${{ steps.app-token.outputs.token }}
